[package]
name = "lagoon"
version = "0.1.0"
authors = ["sourcepirate <E0267819@u.nus.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonic_client = "0.1.2"
rusoto_core = "0.44.0"
rusoto_s3 = "0.44.0"
md5 = "0.7.0"
futures = "0.3.5"