[package]
name = "lagoon"
version = "0.1.0"
authors = ["sourcepirate <E0267819@u.nus.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
